version: "3.3"
services:
  # frontend
    frontend:
        build: ./frontend   
        container_name: pzgm-frontend
        env_file:
          - ./frontend/.env 
        restart: unless-stopped

      # backend
    backend:
        build: ./backend    
        container_name: pzgm-backend
        environment:
          - TZ=Europe/Amsterdam
        env_file:
          - ./backend/api/.env
        links:
          - database
        depends_on:
          - database
        restart: unless-stopped

      # database
    database:
            image: postgres
            restart: always
            environment:
                POSTGRES_PASSWORD: 123456
            ports:
                - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8888:8080

