version: "3.3"
services:
      # database
    db:
      container_name: pzgm-db
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: transcendance
      ports:
          - 2345:5432

      # backend
    backend:
        build:
          context: api
          dockerfile: Dockerfile
        container_name: pzgm-backend
        restart: unless-stopped
        environment:
          - TZ=Europe/Amsterdam
        env_file:
          - ./api/.env
        links:
          - db
        depends_on:
          - db
        ports:
            - 3333:3333

  # frontend
    frontend:
        build:
          context: frontend
          dockerfile: Dockerfile
        container_name: pzgm-frontend
        environment:
          - TZ=Europe/Amsterdam
        env_file:
          - ./frontend/.env 
        restart: unless-stopped
        ports:
          - 3000:3000
          
    adminer:
        container_name: pzgm-adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080